# Generated by Django 4.1.3 on 2023-12-07 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvisitors',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 7, 17, 37, 34, 423035, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sub_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
