# Generated by Django 4.2.3 on 2023-08-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_header_image_alter_menu_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='discription',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
