# Generated by Django 4.1.7 on 2023-12-08 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_dailyvisitors_date_alter_menu_sub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvisitors',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 8, 5, 10, 6, 879208, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
