# Generated by Django 4.2.3 on 2023-08-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_header_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='discription',
            new_name='description',
        ),
    ]
