# Generated by Django 4.1.7 on 2023-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_header_image_alter_menu_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
