# Generated by Django 4.2.3 on 2023-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_menu_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vegnonveg',
            field=models.CharField(max_length=15),
        ),
    ]
