# Generated by Django 4.2.4 on 2023-08-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_item_vegnonveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='daily_visitors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
