# Generated by Django 4.2.4 on 2023-08-12 03:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_menu_daily_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='daily_visitors',
        ),
        migrations.CreateModel(
            name='Daily_visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 8, 12))),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.menu')),
            ],
        ),
    ]
