# Generated by Django 4.2.4 on 2023-08-12 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_daily_visitors_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2023, 8, 12, 3, 48, 41, 1224, tzinfo=datetime.timezone.utc), null=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Daily_visitors',
        ),
    ]
